# Name of workflow to be displyed on Github Console
name: Check PR

# Triggers the workflow on separate events 
on:
  push:
    branches:
      -  '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check Pr
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: check env
        run: env
